### ISSUE TITLE
configure: error: export OPENCOLLADA_CFLAGS

### ISSUE THREAD

**Issue by Nheghathivhistha** [a17r/a17rgentoo#2]
Hello.
It seems that =app-office/libreoffice-4.3.3.2 configure is not happy with check for OPENCOLLADA.
The message is:
-cut-
checking for LIBGLTF... yes
checking whether to enable COLLADA support... yes
checking which OPENCOLLADA to use... external
configure: error: export OPENCOLLADA_CFLAGS
-cut

There is nothing useful in /var/tmp/portage/app-office/libreoffice-4.3.3.2/work/libreoffice-4.3.3.2/config.log.

ENABLE_COLLADA='TRUE'

OPENCOLLADA_CFLAGS=''
OPENCOLLADA_LIBS=''

SYSTEM_OPENCOLLADA='TRUE'

#define HAVE_FEATURE_COLLADA 1

configure:35714: checking whether to enable COLLADA support
configure:35718: result: yes
configure:35723: checking which OPENCOLLADA to use
configure:35726: result: external
configure:35732: error: export OPENCOLLADA_CFLAGS

Ichecked both your version of Collada and in tree Gentoo one, but problem is in Libreoffice configure in my opinion.
Should I report this upstream please?

Thank you.
Best regards, David.

**Comment by a17r** [comment]
I had another go at opencolada support, and it should work now.
